### ISSUE TITLE
Exception: ('Unknown form type:', u'frm')

### ISSUE THREAD

**Issue by lmakarov** [docksal/service-juniper-vpn#3]
There is a non-critical error, which does not seem to cause any issues:

```
Exception: ('Unknown form type:', u'frm')
```

Full log:

```
$ docker logs -f juniper-vpn
2018-09-12 16:17:31,195 CRIT Supervisor running as root (no user in config file)
2018-09-12 16:17:31,212 INFO RPC interface 'supervisor' initialized
2018-09-12 16:17:31,212 INFO supervisord started with pid 8
2018-09-12 16:17:32,218 INFO spawned: 'vpn' with pid 11
2018-09-12 16:17:32,221 INFO spawned: 'proxy-socks' with pid 12
2018-09-12 16:17:32,223 INFO spawned: 'proxy-http' with pid 13
DNS: overly long line in /etc/resolv.conf -- skipping.
Established listening socket on port 8080.
2018-09-12 16:17:33,241 INFO success: vpn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-12 16:17:33,241 INFO success: proxy-socks entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-12 16:17:33,241 INFO success: proxy-http entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/root/.juniper_networks/juniper-vpn-wrap.py", line 463, in <module>
    jvpn.run()
  File "/root/.juniper_networks/juniper-vpn-wrap.py", line 145, in run
    action = self.next_action()
  File "/root/.juniper_networks/juniper-vpn-wrap.py", line 138, in next_action
    raise Exception('Unknown form type:', form.name)
Exception: ('Unknown form type:', u'frm')
2018-09-12 16:17:44,956 INFO exited: vpn (terminated by SIGTERM; not expected)
2018-09-12 16:17:45,960 INFO spawned: 'vpn' with pid 14
2018-09-12 16:17:46,963 INFO success: vpn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Downloading ncLinuxApp.jar...
20180912161755.197919 ncsvc[p15.t15] session.error proxy not found (session.cpp:401)
20180912161755.200837 ncsvc[p15.t15] rmon.error Setting Best route 0 10011ac 0 a0d7b18 eth0 (routemon.cpp:1595)
20180912161755.201273 ncsvc[p15.t15] ncp.error ncpEstablish for IVE secure.autodesk.com with context 0xa0d29c4 (ncp.cpp:556)
20180912161755.338481 ncsvc[p15.t17] dsssl.error Cert hash is not SHA256. len=32 (DSSSLSock.cpp:1906)
20180912161755.364153 ncsvc[p15.t17] ncp.error NCP_ESTABLISH_DONE for IVE secure.autodesk.com (ncp.cpp:2070)
20180912161755.449222 ncsvc[p15.t17] dsssl.error Cert hash is not SHA256. len=32 (DSSSLSock.cpp:1906)
20180912161755.543174 ncsvc[p15.t15] session.error Failed to execute command /sbin/sysctl net.ipv6.conf.tun0.disable_ipv6=1 >/dev/null 2>/dev/null. DSSysCmd::executeAndWait returned 11. (session.cpp:1375)
```

May only be reproducible on certain Pulse Secure VPN server configurations.

**Comment by vitaly-malashevsky** [comment]
Yeah, it happened to me time to time to me using the same server and client configuration. I wan't able to find a way to reproduce it on demand. Seems to be related to a server or media state.

**Comment by lmakarov** [comment]
I no longer have any use for this setup and cannot provide support. I'm going to archive this repo for the time being.
