### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by rvictoria** [docksal/service-juniper-vpn#7]
Hi,
I'm having some problems to connect to vpn. Here the log trace:
Traceback (most recent call last):
  File "./juniper-vpn-wrap.py", line 465, in <module>
    jvpn.run()
  File "./juniper-vpn-wrap.py", line 149, in run
    self.action_login()
  File "./juniper-vpn-wrap.py", line 223, in action_login
    self.br.form['username'] = self.username
  File "build/bdist.linux-x86_64/egg/mechanize/_form_controls.py", line 1947, in __setitem__
  File "build/bdist.linux-x86_64/egg/mechanize/_form_controls.py", line 2338, in find_control
  File "build/bdist.linux-x86_64/egg/mechanize/_form_controls.py", line 2431, in _find_control
mechanize._form_controls.ControlNotFoundError: no control matching name 'username'
Terminated

Can you help me?
Thanks!

**Comment by lmakarov** [comment]
Sorry, I no longer have any use for this setup and cannot provide support. I'm going to archive this repo for the time being.
